version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mflow-backend
    ports:
      - "5173:5173"
    restart: always

  frontend:
    build: ./frontend
    container_name: mflow-frontend
    ports:
      - "5174:5174"
    restart: always
